name: Release

permissions:
  contents: read

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.*
      - install-action-manifest-schema-[0-9]+.[0-9]+.*

defaults:
  run:
    shell: bash --noprofile --norc -CeEuxo pipefail {0}

jobs:
  create-release:
    if: github.repository_owner == 'taiki-e' && !startsWith(github.ref_name, 'install-action-manifest-schema-')
    runs-on: ubuntu-latest
    timeout-minutes: 60
    environment: release
    permissions:
      contents: write # for taiki-e/create-gh-release-action
    steps:
      - uses: taiki-e/checkout-action@v1
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          title: $version
          branch: 'main|v[0-9]+'
          token: ${{ secrets.GITHUB_TOKEN }}

  create-release-manifest-schema:
    if: github.repository_owner == 'taiki-e' && startsWith(github.ref_name, 'install-action-manifest-schema-')
    # TODO: use new rust-release workflow
    uses: taiki-e/github-actions/.github/workflows/create-release.yml@853cebf868aa2dce1470668df24176803e05adc8
    with:
      crates: tools/manifest-schema
      changelog: tools/manifest-schema/CHANGELOG.md
      title: $prefix $version
      prefix: install-action-manifest-schema
    permissions:
      contents: write # for taiki-e/create-gh-release-action
      id-token: write # for rust-lang/crates-io-auth-action
    secrets: inherit
